In [2]:
import os

In [3]:
os.getcwd()

'C:\\Users\\dell\\Documents'

In [4]:
os.chdir('C:/Users/dell/Desktop/datas')

In [5]:
import pandas as pd
import numpy as np

In [6]:
data=pd.read_csv('data.csv')

In [7]:
data

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0      842302         M       17.990         10.38          122.80     1001.0   
1      842517         M       20.570         17.77          132.90     1326.0   
2    84300903         M       19.690         21.25          130.00     1203.0   
3    84348301         M       11.420         20.38           77.58      386.1   
4    84358402         M       20.290         14.34          135.10     1297.0   
5      843786         M       12.450         15.70           82.57      477.1   
6      844359         M       18.250         19.98          119.60     1040.0   
7    84458202         M       13.710         20.83           90.20      577.9   
8      844981         M       13.000         21.82           87.50      519.8   
9    84501001         M       12.460         24.04           83.97      475.9   
10     845636         M       16.020         23.24          102.70      797.8   
11   84610002         M       15.780         17.89          103.60      781.0   
12     846226         M       19.170         24.80          132.40     1123.0   
13     846381         M       15.850         23.95          103.70      782.7   
14   84667401         M       13.730         22.61           93.60      578.3   
15   84799002         M       14.540         27.54           96.73      658.8   
16     848406         M       14.680         20.13           94.74      684.5   
17   84862001         M       16.130         20.68          108.10      798.8   
18     849014         M       19.810         22.15          130.00     1260.0   
19    8510426         B       13.540         14.36           87.46      566.3   
20    8510653         B       13.080         15.71           85.63      520.0   
21    8510824         B        9.504         12.44           60.34      273.9   
22    8511133         M       15.340         14.26          102.50      704.4   
23     851509         M       21.160         23.04          137.20     1404.0   
24     852552         M       16.650         21.38          110.00      904.6   
25     852631         M       17.140         16.40          116.00      912.7   
26     852763         M       14.580         21.53           97.41      644.8   
27     852781         M       18.610         20.25          122.10     1094.0   
28     852973         M       15.300         25.27          102.40      732.4   
29     853201         M       17.570         15.05          115.00      955.1   
..        ...       ...          ...           ...             ...        ...   
539    921362         B        7.691         25.44           48.34      170.4   
540    921385         B       11.540         14.44           74.65      402.9   
541    921386         B       14.470         24.99           95.81      656.4   
542    921644         B       14.740         25.42           94.70      668.6   
543    922296         B       13.210         28.06           84.88      538.4   
544    922297         B       13.870         20.70           89.77      584.8   
545    922576         B       13.620         23.23           87.19      573.2   
546    922577         B       10.320         16.35           65.31      324.9   
547    922840         B       10.260         16.58           65.85      320.8   
548    923169         B        9.683         19.34           61.05      285.7   
549    923465         B       10.820         24.21           68.89      361.6   
550    923748         B       10.860         21.48           68.51      360.5   
551    923780         B       11.130         22.44           71.49      378.4   
552    924084         B       12.770         29.43           81.35      507.9   
553    924342         B        9.333         21.94           59.01      264.0   
554    924632         B       12.880         28.92           82.50      514.3   
555    924934         B       10.290         27.61           65.67      321.4   
556    924964         B       10.160      

In [8]:
from sklearn import preprocessing

In [9]:
data=data.drop(['id'],axis=1)

In [10]:
data

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0           M       17.990         10.38          122.80     1001.0   
1           M       20.570         17.77          132.90     1326.0   
2           M       19.690         21.25          130.00     1203.0   
3           M       11.420         20.38           77.58      386.1   
4           M       20.290         14.34          135.10     1297.0   
5           M       12.450         15.70           82.57      477.1   
6           M       18.250         19.98          119.60     1040.0   
7           M       13.710         20.83           90.20      577.9   
8           M       13.000         21.82           87.50      519.8   
9           M       12.460         24.04           83.97      475.9   
10          M       16.020         23.24          102.70      797.8   
11          M       15.780         17.89          103.60      781.0   
12          M       19.170         24.80          132.40     1123.0   
13          M       15.850         23.95          103.70      782.7   
14          M       13.730         22.61           93.60      578.3   
15          M       14.540         27.54           96.73      658.8   
16          M       14.680         20.13           94.74      684.5   
17          M       16.130         20.68          108.10      798.8   
18          M       19.810         22.15          130.00     1260.0   
19          B       13.540         14.36           87.46      566.3   
20          B       13.080         15.71           85.63      520.0   
21          B        9.504         12.44           60.34      273.9   
22          M       15.340         14.26          102.50      704.4   
23          M       21.160         23.04          137.20     1404.0   
24          M       16.650         21.38          110.00      904.6   
25          M       17.140         16.40          116.00      912.7   
26          M       14.580         21.53           97.41      644.8   
27          M       18.610         20.25          122.10     1094.0   
28          M       15.300         25.27          102.40      732.4   
29          M       17.570         15.05          115.00      955.1   
..        ...          ...           ...             ...        ...   
539         B        7.691         25.44           48.34      170.4   
540         B       11.540         14.44           74.65      402.9   
541         B       14.470         24.99           95.81      656.4   
542         B       14.740         25.42           94.70      668.6   
543         B       13.210         28.06           84.88      538.4   
544         B       13.870         20.70           89.77      584.8   
545         B       13.620         23.23           87.19      573.2   
546         B       10.320         16.35           65.31      324.9   
547         B       10.260         16.58           65.85      320.8   
548         B        9.683         19.34           61.05      285.7   
549         B       10.820         24.21           68.89      361.6   
550         B       10.860         21.48           68.51      360.5   
551         B       11.130         22.44           71.49      378.4   
552         B       12.770         29.43           81.35      507.9   
553         B        9.333         21.94           59.01      264.0   
554         B       12.880         28.92           82.50      514.3   
555         B       10.290         27.61           65.67      321.4   
556         B       10.160         19.59           64.73      311.7   
557         B        9.423         27.88           59.26      271.3   
558         B       14.590         22.68           96.39      657.1   
559         B       11.510         23.93           74.52      403.5   
560         B       14.050         27.15           91.38      600.4   
561         B       11.200         29.37           70.67      386.0   
562         M       15.220         30.62          103.40      716.9   
563         M       20.920  

In [11]:
data.diagnosis.value_counts()

B    357
M    212
Name: diagnosis, dtype: int64

In [12]:
data['diagnosis'].replace(['M','B'],['Malignant','Benign'],inplace=True)

In [13]:
data

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    Malignant       17.990         10.38          122.80     1001.0   
1    Malignant       20.570         17.77          132.90     1326.0   
2    Malignant       19.690         21.25          130.00     1203.0   
3    Malignant       11.420         20.38           77.58      386.1   
4    Malignant       20.290         14.34          135.10     1297.0   
5    Malignant       12.450         15.70           82.57      477.1   
6    Malignant       18.250         19.98          119.60     1040.0   
7    Malignant       13.710         20.83           90.20      577.9   
8    Malignant       13.000         21.82           87.50      519.8   
9    Malignant       12.460         24.04           83.97      475.9   
10   Malignant       16.020         23.24          102.70      797.8   
11   Malignant       15.780         17.89          103.60      781.0   
12   Malignant       19.170         24.80          132.40     1123.0   
13   Malignant       15.850         23.95          103.70      782.7   
14   Malignant       13.730         22.61           93.60      578.3   
15   Malignant       14.540         27.54           96.73      658.8   
16   Malignant       14.680         20.13           94.74      684.5   
17   Malignant       16.130         20.68          108.10      798.8   
18   Malignant       19.810         22.15          130.00     1260.0   
19      Benign       13.540         14.36           87.46      566.3   
20      Benign       13.080         15.71           85.63      520.0   
21      Benign        9.504         12.44           60.34      273.9   
22   Malignant       15.340         14.26          102.50      704.4   
23   Malignant       21.160         23.04          137.20     1404.0   
24   Malignant       16.650         21.38          110.00      904.6   
25   Malignant       17.140         16.40          116.00      912.7   
26   Malignant       14.580         21.53           97.41      644.8   
27   Malignant       18.610         20.25          122.10     1094.0   
28   Malignant       15.300         25.27          102.40      732.4   
29   Malignant       17.570         15.05          115.00      955.1   
..         ...          ...           ...             ...        ...   
539     Benign        7.691         25.44           48.34      170.4   
540     Benign       11.540         14.44           74.65      402.9   
541     Benign       14.470         24.99           95.81      656.4   
542     Benign       14.740         25.42           94.70      668.6   
543     Benign       13.210         28.06           84.88      538.4   
544     Benign       13.870         20.70           89.77      584.8   
545     Benign       13.620         23.23           87.19      573.2   
546     Benign       10.320         16.35           65.31      324.9   
547     Benign       10.260         16.58           65.85      320.8   
548     Benign        9.683         19.34           61.05      285.7   
549     Benign       10.820         24.21           68.89      361.6   
550     Benign       10.860         21.48           68.51      360.5   
551     Benign       11.130         22.44           71.49      378.4   
552     Benign       12.770         29.43           81.35      507.9   
553     Benign        9.333         21.94           59.01      264.0   
554     Benign       12.880         28.92           82.50      514.3   
555     Benign       10.290         27.61           65.67      321.4   
556     Benign       10.160         19.59           64.73      311.7   
557     Benign        9.423         27.88           59.26      271.3   
558     Benign       14.590         22.68           96.39      657.1   
559     Benign       11.510         23.93           74.52      403.5   
560     Benign       14.050         27.15           91.38      600.4   
561     Benign       11.200         29.37           70.67      386.0   
562  Malignant       15.220         30.62    

In [14]:
a=data.loc[:,['radius_mean','area_mean','smoothness_mean']] 
#slicing to get particular columns from the data

In [15]:
a

radius_mean  area_mean  smoothness_mean
0         17.990     1001.0          0.11840
1         20.570     1326.0          0.08474
2         19.690     1203.0          0.10960
3         11.420      386.1          0.14250
4         20.290     1297.0          0.10030
5         12.450      477.1          0.12780
6         18.250     1040.0          0.09463
7         13.710      577.9          0.11890
8         13.000      519.8          0.12730
9         12.460      475.9          0.11860
10        16.020      797.8          0.08206
11        15.780      781.0          0.09710
12        19.170     1123.0          0.09740
13        15.850      782.7          0.08401
14        13.730      578.3          0.11310
15        14.540      658.8          0.11390
16        14.680      684.5          0.09867
17        16.130      798.8          0.11700
18        19.810     1260.0          0.09831
19        13.540      566.3          0.09779
20        13.080      520.0          0.10750
21         9.504      273.9          0.10240
22        15.340      704.4          0.10730
23        21.160     1404.0          0.09428
24        16.650      904.6          0.11210
25        17.140      912.7          0.11860
26        14.580      644.8          0.10540
27        18.610     1094.0          0.09440
28        15.300      732.4          0.10820
29        17.570      955.1          0.09847
..           ...        ...              ...
539        7.691      170.4          0.08668
540       11.540      402.9          0.09984
541       14.470      656.4          0.08837
542       14.740      668.6          0.08275
543       13.210      538.4          0.08671
544       13.870      584.8          0.09578
545       13.620      573.2          0.09246
546       10.320      324.9          0.09434
547       10.260      320.8          0.08877
548        9.683      285.7          0.08491
549       10.820      361.6          0.08192
550       10.860      360.5          0.07431
551       11.130      378.4          0.09566
552       12.770      507.9          0.08276
553        9.333      264.0          0.09240
554       12.880      514.3          0.08123
555       10.290      321.4          0.09030
556       10.160      311.7          0.10030
557        9.423      271.3          0.08123
558       14.590      657.1          0.08473
559       11.510      403.5          0.09261
560       14.050      600.4          0.09929
561       11.200      386.0          0.07449
562       15.220      716.9          0.10480
563       20.920     1347.0          0.10990
564       21.560     1479.0          0.11100
565       20.130     1261.0          0.09780
566       16.600      858.1          0.08455
567       20.600     1265.0          0.11780
568        7.760      181.0          0.05263

[569 rows x 3 columns]

In [16]:
a.describe()

radius_mean    area_mean  smoothness_mean
count   569.000000   569.000000       569.000000
mean     14.127292   654.889104         0.096360
std       3.524049   351.914129         0.014064
min       6.981000   143.500000         0.052630
25%      11.700000   420.300000         0.086370
50%      13.370000   551.100000         0.095870
75%      15.780000   782.700000         0.105300
max      28.110000  2501.000000         0.163400

In [17]:
# to remove randomness and make data consistent normalization is necessary
x=data.iloc[:,1:31]
y=data.iloc[:,0]

In [18]:
x

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
0         17.990         10.38          122.80     1001.0          0.11840   
1         20.570         17.77          132.90     1326.0          0.08474   
2         19.690         21.25          130.00     1203.0          0.10960   
3         11.420         20.38           77.58      386.1          0.14250   
4         20.290         14.34          135.10     1297.0          0.10030   
5         12.450         15.70           82.57      477.1          0.12780   
6         18.250         19.98          119.60     1040.0          0.09463   
7         13.710         20.83           90.20      577.9          0.11890   
8         13.000         21.82           87.50      519.8          0.12730   
9         12.460         24.04           83.97      475.9          0.11860   
10        16.020         23.24          102.70      797.8          0.08206   
11        15.780         17.89          103.60      781.0          0.09710   
12        19.170         24.80          132.40     1123.0          0.09740   
13        15.850         23.95          103.70      782.7          0.08401   
14        13.730         22.61           93.60      578.3          0.11310   
15        14.540         27.54           96.73      658.8          0.11390   
16        14.680         20.13           94.74      684.5          0.09867   
17        16.130         20.68          108.10      798.8          0.11700   
18        19.810         22.15          130.00     1260.0          0.09831   
19        13.540         14.36           87.46      566.3          0.09779   
20        13.080         15.71           85.63      520.0          0.10750   
21         9.504         12.44           60.34      273.9          0.10240   
22        15.340         14.26          102.50      704.4          0.10730   
23        21.160         23.04          137.20     1404.0          0.09428   
24        16.650         21.38          110.00      904.6          0.11210   
25        17.140         16.40          116.00      912.7          0.11860   
26        14.580         21.53           97.41      644.8          0.10540   
27        18.610         20.25          122.10     1094.0          0.09440   
28        15.300         25.27          102.40      732.4          0.10820   
29        17.570         15.05          115.00      955.1          0.09847   
..           ...           ...             ...        ...              ...   
539        7.691         25.44           48.34      170.4          0.08668   
540       11.540         14.44           74.65      402.9          0.09984   
541       14.470         24.99           95.81      656.4          0.08837   
542       14.740         25.42           94.70      668.6          0.08275   
543       13.210         28.06           84.88      538.4          0.08671   
544       13.870         20.70           89.77      584.8          0.09578   
545       13.620         23.23           87.19      573.2          0.09246   
546       10.320         16.35           65.31      324.9          0.09434   
547       10.260         16.58           65.85      320.8          0.08877   
548        9.683         19.34           61.05      285.7          0.08491   
549       10.820         24.21           68.89      361.6          0.08192   
550       10.860         21.48           68.51      360.5          0.07431   
551       11.130         22.44           71.49      378.4          0.09566   
552       12.770         29.43           81.35      507.9          0.08276   
553        9.333         21.94           59.01      264.0          0.09240   
554       12.880         28.92           82.50      514.3          0.08123   
555       10.290         27.61           65.67      321.4          0.09030   
556       10.160         19.59           64.73      311.7          0.10030   
557        9.423         27.88           59.26      271.3          0.08123   
558       14.590         22

In [19]:
y

0      Malignant
1      Malignant
2      Malignant
3      Malignant
4      Malignant
5      Malignant
6      Malignant
7      Malignant
8      Malignant
9      Malignant
10     Malignant
11     Malignant
12     Malignant
13     Malignant
14     Malignant
15     Malignant
16     Malignant
17     Malignant
18     Malignant
19        Benign
20        Benign
21        Benign
22     Malignant
23     Malignant
24     Malignant
25     Malignant
26     Malignant
27     Malignant
28     Malignant
29     Malignant
         ...    
539       Benign
540       Benign
541       Benign
542       Benign
543       Benign
544       Benign
545       Benign
546       Benign
547       Benign
548       Benign
549       Benign
550       Benign
551       Benign
552       Benign
553       Benign
554       Benign
555       Benign
556       Benign
557       Benign
558       Benign
559       Benign
560       Benign
561       Benign
562    Malignant
563    Malignant
564    Malignant
565    Malignant
566    Maligna

In [20]:
#min-max scaler technique to fit data between 0 and 1
#x-min(x)/max(x)-min(x) ratio  all the values are changed to 0 and 1 user defined function
# virtual data to be analysed
minmax=preprocessing.MinMaxScaler(feature_range=(0,1))
minmax.fit(x).transform(x)

array([[ 0.52103744,  0.0226581 ,  0.54598853, ...,  0.91202749,
         0.59846245,  0.41886396],
       [ 0.64314449,  0.27257355,  0.61578329, ...,  0.63917526,
         0.23358959,  0.22287813],
       [ 0.60149557,  0.3902604 ,  0.59574321, ...,  0.83505155,
         0.40370589,  0.21343303],
       ..., 
       [ 0.45525108,  0.62123774,  0.44578813, ...,  0.48728522,
         0.12872068,  0.1519087 ],
       [ 0.64456434,  0.66351031,  0.66553797, ...,  0.91065292,
         0.49714173,  0.45231536],
       [ 0.03686876,  0.50152181,  0.02853984, ...,  0.        ,
         0.25744136,  0.10068215]])

In [21]:
x['area_mean'].describe()

count     569.000000
mean      654.889104
std       351.914129
min       143.500000
25%       420.300000
50%       551.100000
75%       782.700000
max      2501.000000
Name: area_mean, dtype: float64

In [22]:
from sklearn import cross_validation,neighbors
from sklearn.cross_validation import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

C:\Users\dell\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [23]:
x_train

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
559       11.510         23.93           74.52      403.5          0.09261   
380       11.270         12.96           73.16      386.3          0.12370   
30        18.630         25.11          124.80     1088.0          0.10640   
208       13.110         22.54           87.02      529.4          0.10020   
43        13.280         20.28           87.32      545.2          0.10410   
424        9.742         19.12           61.93      289.7          0.10750   
88        12.360         21.80           79.78      466.1          0.08772   
502       12.540         16.32           81.25      476.3          0.11580   
473       12.270         29.97           77.42      465.4          0.07699   
327       12.030         17.93           76.09      446.0          0.07683   
226       10.440         15.46           66.62      329.6          0.10530   
132       16.160         21.54          106.20      809.8          0.10080   
75        16.070         19.65          104.10      817.7          0.09168   
292       12.950         16.02           83.14      513.7          0.10050   
406       16.140         14.86          104.30      800.0          0.09495   
213       17.420         25.56          114.50      948.0          0.10060   
176        9.904         18.06           64.60      302.4          0.09699   
86        14.480         21.46           94.25      648.2          0.09444   
470        9.667         18.49           61.49      289.1          0.08946   
312       12.760         13.37           82.29      504.1          0.08794   
534       10.960         17.62           70.79      365.6          0.09687   
173       11.080         14.71           70.21      372.7          0.10060   
563       20.920         25.09          143.00     1347.0          0.10990   
314        8.597         18.60           54.09      221.2          0.10740   
54        15.100         22.02           97.26      712.8          0.09056   
558       14.590         22.68           96.39      657.1          0.08473   
351       15.750         19.22          107.10      758.6          0.12430   
417       15.500         21.08          102.90      803.1          0.11200   
142       11.430         17.31           73.66      398.0          0.10920   
5         12.450         15.70           82.57      477.1          0.12780   
..           ...           ...             ...        ...              ...   
29        17.570         15.05          115.00      955.1          0.09847   
194       14.860         23.21          100.40      671.4          0.10440   
459        9.755         28.20           61.68      290.9          0.07984   
21         9.504         12.44           60.34      273.9          0.10240   
56        19.210         18.57          125.50     1152.0          0.10530   
460       17.080         27.15          111.20      930.9          0.09898   
42        19.070         24.81          128.30     1104.0          0.09081   
12        19.170         24.80          132.40     1123.0          0.09740   
211       11.840         18.94           75.51      428.0          0.08871   
115       11.930         21.53           76.53      438.6          0.09768   
449       21.100         20.52          138.10     1384.0          0.09684   
520        9.295         13.90           59.96      257.8          0.13710   
375       16.170         16.07          106.30      788.5          0.09880   
61         8.598         20.98           54.66      221.8          0.12430   
360       12.540         18.07           79.42      491.9          0.07436   
227       15.000         15.51           97.45      684.5          0.08371   
10        16.020         23.24          102.70      797.8          0.08206   
38        14.990         25.20           95.54      698.8          0.09387   
510       11.740         14.69           76.31      426.0          0.08099   
272       21.750         20

In [24]:
y_train

559       Benign
380       Benign
30     Malignant
208       Benign
43     Malignant
424       Benign
88        Benign
502       Benign
473       Benign
327       Benign
226       Benign
132    Malignant
75     Malignant
292       Benign
406       Benign
213    Malignant
176       Benign
86     Malignant
470       Benign
312       Benign
534       Benign
173       Benign
563    Malignant
314       Benign
54     Malignant
558       Benign
351    Malignant
417    Malignant
142       Benign
5      Malignant
         ...    
29     Malignant
194    Malignant
459       Benign
21        Benign
56     Malignant
460    Malignant
42     Malignant
12     Malignant
211       Benign
115       Benign
449    Malignant
520       Benign
375       Benign
61        Benign
360       Benign
227       Benign
10     Malignant
38     Malignant
510       Benign
272    Malignant
95     Malignant
329    Malignant
528       Benign
114       Benign
487    Malignant
412       Benign
64     Malignant
450       Beni

In [25]:
x_test

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
394       12.100         17.72           78.07      446.2          0.10290   
527       12.340         12.27           78.94      468.5          0.09003   
217       10.200         17.48           65.05      321.2          0.08054   
505        9.676         13.14           64.12      272.5          0.12550   
533       20.470         20.67          134.70     1299.0          0.09156   
215       13.860         16.93           90.96      578.9          0.10260   
341        9.606         16.84           61.64      280.5          0.08481   
508       16.300         15.70          104.70      819.8          0.09427   
374       13.690         16.07           87.84      579.1          0.08302   
363       16.500         18.29          106.60      838.1          0.09686   
303       10.490         18.61           66.86      334.3          0.10680   
185       10.080         15.11           63.76      317.5          0.09267   
44        13.170         21.81           85.42      531.5          0.09714   
413       14.990         22.11           97.53      693.7          0.08515   
319       12.430         17.00           78.60      477.3          0.07557   
317       18.220         18.87          118.70     1027.0          0.09746   
397       12.800         17.46           83.05      508.3          0.08044   
199       14.450         20.22           94.49      642.7          0.09872   
6         18.250         19.98          119.60     1040.0          0.09463   
33        19.270         26.47          127.90     1162.0          0.09401   
248       10.650         25.22           68.01      347.0          0.09657   
174       10.660         15.15           67.49      349.6          0.08792   
242       11.300         18.19           73.93      389.4          0.09592   
16        14.680         20.13           94.74      684.5          0.09867   
126       13.610         24.69           87.76      572.6          0.09258   
318        9.042         18.90           60.07      244.5          0.09968   
387       13.880         16.16           88.37      596.6          0.07026   
49        13.490         22.30           86.91      561.0          0.08752   
367       12.210         18.02           78.31      458.4          0.09231   
281       11.740         14.02           74.24      427.3          0.07813   
..           ...           ...             ...        ...              ...   
337       18.770         21.43          122.90     1092.0          0.09116   
207       17.010         20.26          109.70      904.3          0.08772   
278       13.590         17.84           86.24      572.3          0.07948   
343       19.680         21.68          129.90     1194.0          0.09797   
545       13.620         23.23           87.19      573.2          0.09246   
127       19.000         18.91          123.40     1138.0          0.08217   
301       12.460         19.89           80.43      471.3          0.08451   
393       21.610         22.28          144.40     1407.0          0.11670   
342       11.060         14.96           71.49      373.9          0.10330   
241       12.420         15.04           78.61      476.5          0.07926   
335       17.060         21.00          111.80      918.6          0.11190   
373       20.640         17.35          134.80     1335.0          0.09446   
236       23.210         26.97          153.50     1670.0          0.09509   
76        13.530         10.94           87.91      559.2          0.12910   
368       21.710         17.25          140.90     1546.0          0.09384   
355       12.560         19.07           81.92      485.8          0.08760   
556       10.160         19.59           64.73      311.7          0.10030   
219       19.530         32.47          128.00     1223.0          0.08420   
121       18.660         17.12          121.40     1077.0          0.10540   
500       15.040         16

In [26]:
y_test

394       Benign
527       Benign
217       Benign
505       Benign
533    Malignant
215    Malignant
341       Benign
508       Benign
374       Benign
363       Benign
303       Benign
185       Benign
44     Malignant
413       Benign
319       Benign
317    Malignant
397       Benign
199    Malignant
6      Malignant
33     Malignant
248       Benign
174       Benign
242       Benign
16     Malignant
126    Malignant
318       Benign
387       Benign
49        Benign
367       Benign
281       Benign
         ...    
337    Malignant
207    Malignant
278       Benign
343    Malignant
545       Benign
127    Malignant
301       Benign
393    Malignant
342       Benign
241       Benign
335    Malignant
373    Malignant
236    Malignant
76        Benign
368    Malignant
355       Benign
556       Benign
219    Malignant
121    Malignant
500       Benign
41     Malignant
422       Benign
385    Malignant
189       Benign
48        Benign
52        Benign
105    Malignant
182    Maligna

In [27]:
clf=neighbors.KNeighborsClassifier()
clf.fit(x_train,y_train)
#clf is a classifier ,KNeighbors method under this we have fit method 

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [28]:
#generating predictions using knn class
y_pred=clf.predict(x_test)

In [29]:
y_pred

array(['Benign', 'Benign', 'Benign', 'Benign', 'Malignant', 'Benign',
       'Benign', 'Malignant', 'Benign', 'Malignant', 'Benign', 'Benign',
       'Malignant', 'Benign', 'Benign', 'Malignant', 'Benign', 'Malignant',
       'Malignant', 'Malignant', 'Benign', 'Benign', 'Benign', 'Malignant',
       'Malignant', 'Benign', 'Benign', 'Benign', 'Benign', 'Benign',
       'Benign', 'Benign', 'Benign', 'Benign', 'Benign', 'Malignant',
       'Benign', 'Benign', 'Malignant', 'Malignant', 'Benign', 'Malignant',
       'Benign', 'Benign', 'Malignant', 'Benign', 'Benign', 'Benign',
       'Malignant', 'Malignant', 'Benign', 'Benign', 'Benign', 'Malignant',
       'Benign', 'Benign', 'Malignant', 'Malignant', 'Benign', 'Malignant',
       'Benign', 'Benign', 'Malignant', 'Malignant', 'Benign', 'Benign',
       'Benign', 'Benign', 'Benign', 'Malignant', 'Benign', 'Malignant',
       'Malignant', 'Benign', 'Benign', 'Benign', 'Benign', 'Benign',
       'Malignant', 'Malignant', 'Benign', 'Benign'

In [30]:
#confusion matix is table to describe performance of classification model
#true positivemodel is more ,model is more accurate
from sklearn.metrics import confusion_matrix
clf_cm_test=confusion_matrix(y_test,y_pred)
clf_cm_test



array([[65,  2],
       [ 6, 41]], dtype=int64)

In [31]:
# k value in knn is by default is sqroot(train)
#calculate acuuracy
accuracy=clf.score(x_test,y_test)

In [32]:
accuracy

0.92982456140350878

In [33]:
from sklearn.svm import SVC
sc=SVC(kernel='rbf')
sc_classifier=sc.fit(x_train,y_train)

In [34]:
sc_classifier

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [35]:
svc_y_test=sc_classifier.predict(x_test)
print(svc_y_test)

['Benign' 'Benign' 'Benign' 'Benign' 'Benign' 'Benign' 'Benign' 'Benign'
 'Benign' 'Benign' 'Benign' 'Benign' 'Benign' 'Benign' 'Benign' 'Benign'
 'Benign' 'Benign' 'Benign' 'Benign' 'Benign' 'Benign' 'Benign' 'Benign'
 'Benign' 'Benign' 'Benign' 'Benign' 'Benign' 'Benign' 'Benign' 'Benign'
 'Benign' 'Benign' 'Benign' 'Benign' 'Benign' 'Benign' 'Benign' 'Benign'
 'Benign' 'Benign' 'Benign' 'Benign' 'Benign' 'Benign' 'Benign' 'Benign'
 'Benign' 'Benign' 'Benign' 'Benign' 'Benign' 'Benign' 'Benign' 'Benign'
 'Benign' 'Benign' 'Benign' 'Benign' 'Benign' 'Benign' 'Benign' 'Benign'
 'Benign' 'Benign' 'Benign' 'Benign' 'Benign' 'Benign' 'Benign' 'Benign'
 'Benign' 'Benign' 'Benign' 'Benign' 'Benign' 'Benign' 'Benign' 'Benign'
 'Benign' 'Benign' 'Benign' 'Benign' 'Benign' 'Benign' 'Benign' 'Benign'
 'Benign' 'Benign' 'Benign' 'Benign' 'Benign' 'Benign' 'Benign' 'Benign'
 'Benign' 'Benign' 'Benign' 'Benign' 'Benign' 'Benign' 'Benign' 'Benign'
 'Benign' 'Benign' 'Benign' 'Benign' 'Benign' 'Beni

In [36]:
svc_y_train=sc_classifier.predict(x_train)
print(svc_y_train)

['Benign' 'Benign' 'Malignant' 'Benign' 'Malignant' 'Benign' 'Benign'
 'Benign' 'Benign' 'Benign' 'Benign' 'Malignant' 'Malignant' 'Benign'
 'Benign' 'Malignant' 'Benign' 'Malignant' 'Benign' 'Benign' 'Benign'
 'Benign' 'Malignant' 'Benign' 'Malignant' 'Benign' 'Malignant' 'Malignant'
 'Benign' 'Malignant' 'Benign' 'Malignant' 'Benign' 'Benign' 'Benign'
 'Benign' 'Malignant' 'Benign' 'Benign' 'Benign' 'Benign' 'Benign' 'Benign'
 'Malignant' 'Malignant' 'Malignant' 'Malignant' 'Benign' 'Benign'
 'Malignant' 'Malignant' 'Benign' 'Benign' 'Benign' 'Benign' 'Malignant'
 'Benign' 'Malignant' 'Benign' 'Benign' 'Benign' 'Benign' 'Malignant'
 'Benign' 'Benign' 'Benign' 'Malignant' 'Benign' 'Malignant' 'Benign'
 'Malignant' 'Benign' 'Benign' 'Benign' 'Benign' 'Malignant' 'Malignant'
 'Benign' 'Benign' 'Benign' 'Benign' 'Benign' 'Benign' 'Malignant' 'Benign'
 'Benign' 'Benign' 'Benign' 'Malignant' 'Benign' 'Benign' 'Malignant'
 'Benign' 'Benign' 'Benign' 'Benign' 'Benign' 'Benign' 'Benign' 'Beni

In [37]:
#confusion matix is table to describe performance of classification model
#true positivemodel is more ,model is more accurate
from sklearn.metrics import confusion_matrix
clf_svc_test=confusion_matrix(y_test,svc_y_test)
clf_svc_test



array([[67,  0],
       [47,  0]], dtype=int64)

In [38]:
#confusion matix is table to describe performance of classification model
#true positivemodel is more ,model is more accurate
from sklearn.metrics import confusion_matrix
clf_svc_train=confusion_matrix(y_train,svc_y_train)
clf_svc_train



array([[290,   0],
       [  0, 165]], dtype=int64)

In [39]:
from sklearn.metrics import accuracy_score
svc_acc_test=accuracy_score(y_test,svc_y_test)
svc_acc_test

0.58771929824561409

In [40]:
example_measures=np.array([15.44,12.54,150.9,998,0.2345,0.3452,0.2891,0.1234,0.3421,0.06879,2.076,0.8079,7.274,168.7,0.009786,0.03804,0.04372,0.02785,0.02002,0.007621,28.75,16.44,192.7,2025,0.1723,0.7752,0.7121,0.3421,0.4802,0.1278])
example_measures=example_measures.reshape(1,-1)

In [41]:
example_measures

array([[  1.54400000e+01,   1.25400000e+01,   1.50900000e+02,
          9.98000000e+02,   2.34500000e-01,   3.45200000e-01,
          2.89100000e-01,   1.23400000e-01,   3.42100000e-01,
          6.87900000e-02,   2.07600000e+00,   8.07900000e-01,
          7.27400000e+00,   1.68700000e+02,   9.78600000e-03,
          3.80400000e-02,   4.37200000e-02,   2.78500000e-02,
          2.00200000e-02,   7.62100000e-03,   2.87500000e+01,
          1.64400000e+01,   1.92700000e+02,   2.02500000e+03,
          1.72300000e-01,   7.75200000e-01,   7.12100000e-01,
          3.42100000e-01,   4.80200000e-01,   1.27800000e-01]])

In [42]:
prediction=clf.predict(example_measures)
print(prediction)

['Malignant']


In [43]:
from sklearn.metrics import accuracy_score
svc_acc_train=accuracy_score(y_train,svc_y_train)
svc_acc_train

1.0

In [44]:
from sklearn.linear_model.logistic import LogisticRegression

In [45]:
cls=LogisticRegression(random_state=0)

In [46]:
lr_cls=cls.fit(x_train,y_train)

In [47]:
lr_cls

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [48]:
lr_y_test=lr_cls.predict(x_test)
lr_y_test

array(['Benign', 'Benign', 'Benign', 'Benign', 'Malignant', 'Benign',
       'Benign', 'Benign', 'Benign', 'Benign', 'Benign', 'Benign',
       'Benign', 'Malignant', 'Benign', 'Malignant', 'Benign', 'Malignant',
       'Malignant', 'Malignant', 'Benign', 'Benign', 'Benign', 'Malignant',
       'Malignant', 'Benign', 'Benign', 'Benign', 'Benign', 'Benign',
       'Benign', 'Benign', 'Benign', 'Benign', 'Benign', 'Malignant',
       'Benign', 'Benign', 'Malignant', 'Malignant', 'Benign', 'Malignant',
       'Benign', 'Benign', 'Malignant', 'Benign', 'Benign', 'Benign',
       'Malignant', 'Malignant', 'Benign', 'Benign', 'Benign', 'Malignant',
       'Benign', 'Benign', 'Malignant', 'Malignant', 'Benign', 'Malignant',
       'Benign', 'Benign', 'Malignant', 'Malignant', 'Benign', 'Benign',
       'Benign', 'Benign', 'Benign', 'Malignant', 'Benign', 'Malignant',
       'Malignant', 'Benign', 'Benign', 'Malignant', 'Benign', 'Malignant',
       'Malignant', 'Malignant', 'Malignant', 'Beni

In [49]:
from sklearn.metrics import confusion_matrix
lr_cm_test=confusion_matrix(y_test,lr_y_test)
lr_cm_test

array([[66,  1],
       [ 4, 43]], dtype=int64)

In [50]:
from sklearn.metrics import accuracy_score
lr_accu_test=accuracy_score(y_test,lr_y_test)

In [51]:
lr_accu_test

0.95614035087719296

In [52]:
lr_y_train=cls.predict(x_train)

In [53]:

lr_accu_train=accuracy_score(y_train,lr_y_train)

In [54]:
lr_accu_train

0.9538461538461539

In [55]:
y_test.shape,lr_y_test.shape

((114,), (114,))

In [56]:
from sklearn.metrics import precision_score,classification_report
lr_precision_test=classification_report(y_test,lr_y_test)
print(lr_precision_test)

             precision    recall  f1-score   support

     Benign       0.94      0.99      0.96        67
  Malignant       0.98      0.91      0.95        47

avg / total       0.96      0.96      0.96       114



In [57]:
from sklearn.metrics import precision_score,classification_report
sv_precision_test=classification_report(y_test,svc_y_test)
print(sv_precision_test)

             precision    recall  f1-score   support

     Benign       0.59      1.00      0.74        67
  Malignant       0.00      0.00      0.00        47

avg / total       0.35      0.59      0.44       114



C:\Users\dell\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [58]:
from sklearn.metrics import precision_score,classification_report
sv_precision_train=classification_report(y_train,svc_y_train)
print(sv_precision_train)

             precision    recall  f1-score   support

     Benign       1.00      1.00      1.00       290
  Malignant       1.00      1.00      1.00       165

avg / total       1.00      1.00      1.00       455



In [59]:
from sklearn.tree import DecisionTreeClassifier

In [60]:
dtc_clf=DecisionTreeClassifier()

In [61]:
dtc_clf.fit(x_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [62]:
dtc_clf

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [63]:
dtc_y_train=dtc_clf.predict(x_train)
dtc_y_train

array(['Benign', 'Benign', 'Malignant', 'Benign', 'Malignant', 'Benign',
       'Benign', 'Benign', 'Benign', 'Benign', 'Benign', 'Malignant',
       'Malignant', 'Benign', 'Benign', 'Malignant', 'Benign', 'Malignant',
       'Benign', 'Benign', 'Benign', 'Benign', 'Malignant', 'Benign',
       'Malignant', 'Benign', 'Malignant', 'Malignant', 'Benign',
       'Malignant', 'Benign', 'Malignant', 'Benign', 'Benign', 'Benign',
       'Benign', 'Malignant', 'Benign', 'Benign', 'Benign', 'Benign',
       'Benign', 'Benign', 'Malignant', 'Malignant', 'Malignant',
       'Malignant', 'Benign', 'Benign', 'Malignant', 'Malignant', 'Benign',
       'Benign', 'Benign', 'Benign', 'Malignant', 'Benign', 'Malignant',
       'Benign', 'Benign', 'Benign', 'Benign', 'Malignant', 'Benign',
       'Benign', 'Benign', 'Malignant', 'Benign', 'Malignant', 'Benign',
       'Malignant', 'Benign', 'Benign', 'Benign', 'Benign', 'Malignant',
       'Malignant', 'Benign', 'Benign', 'Benign', 'Benign', 'Benign',
 

In [64]:
dtc_y_test=dtc_clf.predict(x_test)
dtc_y_test

array(['Benign', 'Benign', 'Benign', 'Benign', 'Malignant', 'Malignant',
       'Benign', 'Benign', 'Benign', 'Malignant', 'Benign', 'Benign',
       'Benign', 'Benign', 'Benign', 'Malignant', 'Benign', 'Malignant',
       'Malignant', 'Malignant', 'Benign', 'Benign', 'Benign', 'Malignant',
       'Benign', 'Benign', 'Benign', 'Benign', 'Benign', 'Benign',
       'Benign', 'Benign', 'Benign', 'Benign', 'Benign', 'Malignant',
       'Benign', 'Benign', 'Malignant', 'Malignant', 'Benign', 'Malignant',
       'Benign', 'Benign', 'Malignant', 'Benign', 'Benign', 'Benign',
       'Malignant', 'Malignant', 'Benign', 'Benign', 'Benign', 'Malignant',
       'Benign', 'Benign', 'Malignant', 'Benign', 'Benign', 'Benign',
       'Benign', 'Benign', 'Malignant', 'Malignant', 'Benign', 'Benign',
       'Benign', 'Benign', 'Benign', 'Malignant', 'Benign', 'Malignant',
       'Malignant', 'Benign', 'Benign', 'Malignant', 'Benign', 'Malignant',
       'Malignant', 'Malignant', 'Benign', 'Benign', 'Mal

In [65]:
from sklearn.metrics import confusion_matrix
dtc_cm_test=confusion_matrix(y_test,dtc_y_test)
dtc_cm_test

array([[66,  1],
       [ 8, 39]], dtype=int64)

In [66]:
from sklearn.metrics import confusion_matrix
dtc_cm_train=confusion_matrix(y_train,dtc_y_train)
dtc_cm_train

array([[290,   0],
       [  0, 165]], dtype=int64)

In [67]:
from sklearn.metrics import accuracy_score
dtc_accu_test=accuracy_score(y_test,dtc_y_test)

In [68]:
dtc_accu_test

0.92105263157894735

In [69]:
dtc_accu_train=accuracy_score(y_train,dtc_y_train)
dtc_accu_train

1.0

In [70]:
from sklearn.metrics import precision_score,classification_report
dtc_precision_train=classification_report(y_train,dtc_y_train)
print(dtc_precision_train)

             precision    recall  f1-score   support

     Benign       1.00      1.00      1.00       290
  Malignant       1.00      1.00      1.00       165

avg / total       1.00      1.00      1.00       455



In [71]:
from sklearn.metrics import precision_score,classification_report
dtc_precision_test=classification_report(y_test,dtc_y_test)
print(dtc_precision_test)

             precision    recall  f1-score   support

     Benign       0.89      0.99      0.94        67
  Malignant       0.97      0.83      0.90        47

avg / total       0.93      0.92      0.92       114



In [72]:
from sklearn.ensemble import RandomForestClassifier

In [73]:
rmf=RandomForestClassifier(max_depth=3,random_state=0)

In [74]:
rf_classi=rmf.fit(x_train,y_train)

In [75]:
rf_classi

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=3, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [76]:
rf_y_test=rf_classi.predict(x_test)

In [77]:
rf_y_test

array(['Benign', 'Benign', 'Benign', 'Benign', 'Malignant', 'Malignant',
       'Benign', 'Benign', 'Benign', 'Benign', 'Benign', 'Benign',
       'Benign', 'Benign', 'Benign', 'Malignant', 'Benign', 'Malignant',
       'Malignant', 'Malignant', 'Benign', 'Benign', 'Benign', 'Malignant',
       'Benign', 'Benign', 'Benign', 'Benign', 'Benign', 'Benign',
       'Benign', 'Benign', 'Benign', 'Benign', 'Benign', 'Malignant',
       'Benign', 'Benign', 'Malignant', 'Malignant', 'Benign', 'Malignant',
       'Benign', 'Benign', 'Malignant', 'Benign', 'Benign', 'Benign',
       'Malignant', 'Malignant', 'Benign', 'Benign', 'Benign', 'Malignant',
       'Benign', 'Benign', 'Malignant', 'Benign', 'Benign', 'Benign',
       'Benign', 'Benign', 'Malignant', 'Malignant', 'Benign', 'Benign',
       'Benign', 'Benign', 'Benign', 'Malignant', 'Benign', 'Malignant',
       'Malignant', 'Benign', 'Benign', 'Malignant', 'Benign', 'Malignant',
       'Malignant', 'Malignant', 'Malignant', 'Benign', 'Mal

In [78]:
rf_y_train=rf_classi.predict(x_train)

In [79]:
rf_y_train

array(['Benign', 'Benign', 'Malignant', 'Benign', 'Malignant', 'Benign',
       'Benign', 'Benign', 'Benign', 'Benign', 'Benign', 'Malignant',
       'Malignant', 'Benign', 'Benign', 'Malignant', 'Benign', 'Benign',
       'Benign', 'Benign', 'Benign', 'Benign', 'Malignant', 'Benign',
       'Malignant', 'Benign', 'Malignant', 'Malignant', 'Benign',
       'Malignant', 'Benign', 'Malignant', 'Benign', 'Benign', 'Benign',
       'Benign', 'Malignant', 'Benign', 'Benign', 'Benign', 'Benign',
       'Benign', 'Benign', 'Malignant', 'Malignant', 'Malignant',
       'Malignant', 'Benign', 'Benign', 'Malignant', 'Malignant', 'Benign',
       'Benign', 'Benign', 'Benign', 'Malignant', 'Benign', 'Malignant',
       'Benign', 'Benign', 'Benign', 'Benign', 'Malignant', 'Benign',
       'Benign', 'Benign', 'Malignant', 'Benign', 'Malignant', 'Benign',
       'Malignant', 'Benign', 'Benign', 'Benign', 'Benign', 'Malignant',
       'Malignant', 'Benign', 'Benign', 'Benign', 'Benign', 'Benign',
    

In [80]:
from sklearn.metrics import confusion_matrix
rf_cm_test=confusion_matrix(y_test,rf_y_test)
rf_cm_test

array([[67,  0],
       [ 6, 41]], dtype=int64)

In [81]:
from sklearn.metrics import confusion_matrix
rf_cm_train=confusion_matrix(y_train,rf_y_train)
rf_cm_train

array([[289,   1],
       [  9, 156]], dtype=int64)

In [82]:
from sklearn.metrics import accuracy_score
rf_accu_test=accuracy_score(y_test,rf_y_test)

In [83]:
rf_accu_test

0.94736842105263153

In [84]:
from sklearn.metrics import accuracy_score
rf_accu_train=accuracy_score(y_train,rf_y_train)

In [85]:
rf_accu_train

0.97802197802197799

In [86]:
from sklearn.metrics import precision_score,classification_report
rf_precision_test=classification_report(y_test,rf_y_test)
print(rf_precision_test)

             precision    recall  f1-score   support

     Benign       0.92      1.00      0.96        67
  Malignant       1.00      0.87      0.93        47

avg / total       0.95      0.95      0.95       114



In [87]:
from sklearn.metrics import precision_score,classification_report
dtc_precision_train=classification_report(y_train,dtc_y_train)
print(dtc_precision_train)

             precision    recall  f1-score   support

     Benign       1.00      1.00      1.00       290
  Malignant       1.00      1.00      1.00       165

avg / total       1.00      1.00      1.00       455



In [89]:
from sklearn import model_selection
from sklearn.ensemble import AdaBoostClassifier
seed=7
num_trees=30
kfold=model_selection.KFold(n_splits=10,random_state=seed)
model=AdaBoostClassifier(n_estimators=num_trees,random_state=seed)
results=model_selection.cross_val_score(model,x_train,y_train,cv=kfold)

In [90]:
results

array([ 0.95652174,  0.97826087,  1.        ,  0.93478261,  0.97826087,
        0.91111111,  0.93333333,  1.        ,  0.95555556,  0.95555556])

In [91]:
kfold

KFold(n_splits=10, random_state=7, shuffle=False)

In [92]:
model

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=1.0, n_estimators=30, random_state=7)