In [2]:
import numpy as np

In [3]:
np?

In [4]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [6]:
np.array([1,2,6.8])

array([ 1. ,  2. ,  6.8])

In [7]:
%%timeit
list1=[1,2,3,4]
list2=[5,6,7,8]

1000000 loops, best of 3: 379 ns per loop


In [8]:
%%timeit
np_array1=np.arange(5000000)

The slowest run took 8.53 times longer than the fastest. This could mean that an intermediate result is being cached.
100 loops, best of 3: 13.6 ms per loop


In [9]:
np.array([range(i,i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [12]:
from numpy import array
from numpy import mean
from numpy import var
t=array([1,2,3,4,5,6,7,8,9])
r=mean(t)
v=var(t)
print(r)


5.0


In [14]:
from numpy import array
from numpy import mean
from numpy import var
t=array([1,2,3,4,5,6,7,8,9])
r=mean(t)
v=var(t)
print(v)


6.66666666667


In [15]:
import pandas as pd

In [20]:
s=pd.Series([1,2,3,np.nan,5,6],index=['a','b','c','d','e','f'])
print(s)

a    1.0
b    2.0
c    3.0
d    NaN
e    5.0
f    6.0
dtype: float64


In [22]:
d={'gender':['M','F','M'],"emp_id":[1,2,3],'age':[12,34,56]}
df=pd.DataFrame(d,columns={'emp_id','age','gender'})
print(df)

   emp_id gender  age
0       1      M   12
1       2      F   34
2       3      M   56


In [23]:
import os
os.getcwd()

'C:\\Users\\dell\\Documents'

In [26]:
os.chdir(D:/data)

SyntaxError: invalid syntax (<ipython-input-26-7d3d2ca589bc>, line 1)

In [27]:
os.chdir(D:/data)

SyntaxError: invalid syntax (<ipython-input-27-7d3d2ca589bc>, line 1)

In [34]:
os.chdir('C:/Users/dell/Desktop/datas')

In [35]:
os.getcwd()

'C:\\Users\\dell\\Desktop\\datas'

In [31]:
data1=pd.read_csv("sales.csv")

OSError: File b'sales.csv' does not exist

In [32]:
data1

NameError: name 'data1' is not defined

In [36]:
os.chdir('C:/Users/dell/Desktop/datas')

In [37]:
os.getcwd()

'C:\\Users\\dell\\Desktop\\datas'

In [38]:
data1=pd.read_csv("sales.csv")

In [39]:
data1

Sales Executive       Name  Gender  Age   Location  Sales ( in Rs)
0                 1     Mahesh    Male   25  Hyderabad              50
1                 2     Suresh    Male   22  Hyderabad              75
2                 3      Vijay    Male   20  Bangalore              11
3                 4     Ramesh    Male   27  Bangalore              77
4                 5   Jagadish    Male   28     Mumbai              45
5                 6     Harish    Male   24  Hyderabad              52
6                 7      Karan    Male   24  Bangalore              26
7                 8       Raju    Male   23     Mumbai              24
8                 9       Maya  Female   24     Mumbai              28
9                10       Rani  Female   30     Mumbai              31
10               11    Lakshmi  Female   19  Bangalore              36
11               12      Roopa  Female   24  Hyderabad              72
12               13     Sravya  Female   26  Hyderabad              69
13               14     Sruthi  Female   26  Hyderabad              51
14               15     Swetha  Female   21  Bangalore              34
15               16  Aishwarya  Female   24  Bangalore              40
16               17    Madhavi  Female   29     Mumbai              18
17               18     Rajini  Female   27     Mumbai              35
18               19    Haritha  Female   24  Hyderabad              29
19               20     Swathi  Female   25  Hyderabad              68